### ISSUE TITLE
TypeError: extensions.join is not a function

### ISSUE THREAD

**Issue by jacopo69** [garystubbings/nativescript-simple-filepicker#2]
Dear Gary,
your plugin is very useful.

I have some trouble in passing any "extensions" parameter: I always receive the error above.

**Comment by garystubbings** [comment]
> Dear Gary,
> your plugin is very useful.
> 
> I have some trouble in passing any "extensions" parameter: I always receive the error above.

Is this in Android? I'll take a look.

I intend to improve the capability for Android in the near future as I also need to support accessing SMB shares for one of my projects, albeit probably though another app. If you leave it blank for now it will default to all files types... I appreciate this is probably not what you want though!

**Comment by garystubbings** [comment]
fixed in #3
